const Constants = {
  SUBMIT_TEXTAREA: "SUBMIT_TEXTAREA",
  SUBMIT_VOICENOTE: "SUBMIT_VOICENOTE",
  SUBMIT_IMAGE: "SUBMIT_IMAGE",

  RECEIVED_OLD_MESSAGES: "RECEIVED_OLD_MESSAGES",
  CHANGE_WINDOW_SIZE: "CHANGE_WINDOW_SIZE",
  BEGIN_API_CALL:"BEGIN_API_CALL",

};

export default Constants;
