const Constants = {
  SUBMIT_TEXTAREA: "SUBMIT_TEXTAREA",
  SUBMIT_VOICENOTE: "SUBMIT_VOICENOTE",
  SUBMIT_IMAGE: "SUBMIT_IMAGE",
  DISPLAY_CHOICE: "DISPLAY_CHOICE",
  DISPLAY_CARD: "DISPLAY_CARD",
  RECEIVED_OLD_MESSAGES: "RECEIVED_OLD_MESSAGES",
  CHANGE_WINDOW_SIZE: "CHANGE_WINDOW_SIZE",
  SELECT_IMAGES: "SELECT_IMAGES",
  BEGIN_API_CALL:"BEGIN_API_CALL",
  END_API_CALL:"END_API_CALL",
  REMOVE_IMAGES:"REMOVE_IMAGES",
  SUBMIT_RATING:"SUBMIT_RATING",
  TEMPLATE_TO_DELETE:"TEMPLATE_TO_DELETE"
};

export default Constants;
